import Head from "next/head"
import styles from '@/styles/Home.module.css'

const AboutUs = () => {
  return (
    <>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          Hello guys! This is the aboutUs page
        </div>
      </main>
    </>
  )
}

export default AboutUs