import Head from 'next/head'
import styles from '@/styles/Home.module.css'


const Home = () => {
  return (
    <>
      <Head>
        <title>All users:</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          Hello guys! This is the index page for users
        </div>
      </main>
    </>
  )
}

export default Home